[[main]]
  name = "大师投资案例"
  identifier = "cases_dropdown"
  weight = 1

[[main]]
  name = "巴菲特"
  parent = "cases_dropdown"
  url = "/zh/tags/巴菲特/"
  weight = 1

[[main]]
  name = "查理芒格"
  parent = "cases_dropdown"
  url = "/zh/tags/查理芒格/"
  weight = 2

[[main]]
  name = "段永平"
  parent = "cases_dropdown"
  url = "/zh/tags/段永平/"
  weight = 3

[[main]]
  name = "但斌"
  parent = "cases_dropdown"
  url = "/zh/tags/但斌/"
  weight = 4

[[main]]
  name = "比尔阿克曼"
  parent = "cases_dropdown"
  url = "/zh/tags/比尔阿克曼/"
  weight = 5




