defaultAppearance = "dark"
disableLanguageSwitchingButton = false
logo = "images/logo.png"

[homepage]
  layout = "background"
  showRecent = true
  showRecentItems = 6
  cardView = true

[header]
  layout = "basic"

[footer]
  showThemeAttribution = false
